from django.urls import path
from .views import (
    channel_detail,
    channel_messages_latest,
    channel_list,
    delete_channel,
    delete_direct_message,
    delete_message,
    delete_voice_channel,
    direct_messages,
    direct_messages_latest,
    home,
    join_channel,
    join_voice_channel,
    mark_notifications_read,
    notifications_list,
    notifications_state,
    search,
    toggle_reaction,
    voice_channel_detail,
)

urlpatterns = [
    path('', home, name='home'),
    path('channels/', channel_list, name='channels'),
    path('channels/<int:channel_id>/messages/latest/', channel_messages_latest, name='channel_messages_latest'),
    path('channels/<int:channel_id>/', channel_detail, name='channel_detail'),
    path('channels/<int:channel_id>/join/', join_channel, name='join_channel'),
    path('channels/<int:channel_id>/delete/', delete_channel, name='delete_channel'),
    path('voice/<int:voice_channel_id>/', voice_channel_detail, name='voice_channel_detail'),
    path('voice/<int:voice_channel_id>/join/', join_voice_channel, name='join_voice_channel'),
    path('voice/<int:voice_channel_id>/delete/', delete_voice_channel, name='delete_voice_channel'),
    path('messages/delete/<int:message_id>/', delete_message, name='delete_message'),
    path('messages/<int:message_id>/react/<str:emoji>/', toggle_reaction, name='toggle_reaction'),
    path('dm/<int:user_id>/', direct_messages, name='direct_messages'),
    path('dm/<int:user_id>/latest/', direct_messages_latest, name='direct_messages_latest'),
    path('dm/messages/delete/<int:message_id>/', delete_direct_message, name='delete_direct_message'),
    path('notifications/', notifications_list, name='notifications'),
    path('notifications/state/', notifications_state, name='notifications_state'),
    path('notifications/read/', mark_notifications_read, name='mark_notifications_read'),
    path('search/', search, name='search'),
]
